baseURL:      "/"
languageCode: "en-au"
title:        "Taylored Technology"
theme:        "kube"
description:  "Uniting Humanity with the Gift of Technology"
Paginate:     4
Params:
  RSSLink:    "/index.xml"
  author:     "Taylored Technology" # add your company name
  github:     "TayloredTechnology" # add your github profile name
  twitter:    "techtaylored" # add your twitter profile

menu:
  main:
    - name:   "About"
      weight: -200
      url:    "/about/"
    # - name: "Blog"
    #   weight: -180
    #   url:  "/blog/"
    - name:   "Services"
      weight: -160
      url:    "/services/"
    - name:   "Products"
      weight: -140
      url:    "/products/"
    - name:   "Contact"
      weight: -120
      url:    "/contact/"
